version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Application exposed on port 8080
    stdin_open: true
    tty: true

  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    ports:
      - "8081:8080" # Jenkins UI exposed on port 8081
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS=true

  sonarqube:
    image: sonarqube:8.9-community
    ports:
      - "9000:9000" # SonarQube UI exposed on port 9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_PORT=9000

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    ports:
      - "9888:8080" # ZAP proxy exposed on port 9888
    command:
    - zap.sh
    - -daemon
    - -port
    - "8080"
    - -host
    - "0.0.0.0"
    - -config
    - "api.addrs.addr.name=.*"
    - -config
    - "api.addrs.addr.regex=true"
    - -config
    - "api.disablekey=true"

volumes:
  jenkins_home: